title: ProtoQuick, Inc. | Bay Area Prototyping Machine Shop and Injection Molder
email: info@proto-quick.com
description: >- # this means to ignore newlines until "baseurl:"
  Need help with your latest prototype or production Design from an ISO certified shop? Look no further.  We are a Bay Area machine shop with EDM & CNC machining specializing in in-house custom tooling and short-run and long-run injection molded parts serving Silicon Valley especially.  Located in Northern California, San Leandro, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://proto-quick.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

source: ./src
destination: ./build

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
